// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: internal/proto/example.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BarEnum_Enum int32

const (
	BarEnum_UNKNOWN BarEnum_Enum = 0
	BarEnum_VALUE_1 BarEnum_Enum = 1
	BarEnum_VALUE_2 BarEnum_Enum = 2
)

// Enum value maps for BarEnum_Enum.
var (
	BarEnum_Enum_name = map[int32]string{
		0: "UNKNOWN",
		1: "VALUE_1",
		2: "VALUE_2",
	}
	BarEnum_Enum_value = map[string]int32{
		"UNKNOWN": 0,
		"VALUE_1": 1,
		"VALUE_2": 2,
	}
)

func (x BarEnum_Enum) Enum() *BarEnum_Enum {
	p := new(BarEnum_Enum)
	*p = x
	return p
}

func (x BarEnum_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BarEnum_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_example_proto_enumTypes[0].Descriptor()
}

func (BarEnum_Enum) Type() protoreflect.EnumType {
	return &file_internal_proto_example_proto_enumTypes[0]
}

func (x BarEnum_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BarEnum_Enum.Descriptor instead.
func (BarEnum_Enum) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_example_proto_rawDescGZIP(), []int{2, 0}
}

type Foo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StringField string  `protobuf:"bytes,1,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	Int32Field  int32   `protobuf:"varint,2,opt,name=int32_field,json=int32Field,proto3" json:"int32_field,omitempty"`
	Int64Field  int64   `protobuf:"varint,3,opt,name=int64_field,json=int64Field,proto3" json:"int64_field,omitempty"`
	Uint32Field uint32  `protobuf:"varint,4,opt,name=uint32_field,json=uint32Field,proto3" json:"uint32_field,omitempty"`
	Uint64Field uint64  `protobuf:"varint,5,opt,name=uint64_field,json=uint64Field,proto3" json:"uint64_field,omitempty"`
	DoubleField float64 `protobuf:"fixed64,6,opt,name=double_field,json=doubleField,proto3" json:"double_field,omitempty"`
	FloatField  float32 `protobuf:"fixed32,7,opt,name=float_field,json=floatField,proto3" json:"float_field,omitempty"`
	BoolField   bool    `protobuf:"varint,8,opt,name=bool_field,json=boolField,proto3" json:"bool_field,omitempty"`
	BytesField  []byte  `protobuf:"bytes,9,opt,name=bytes_field,json=bytesField,proto3" json:"bytes_field,omitempty"`
}

func (x *Foo) Reset() {
	*x = Foo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_internal_proto_example_proto_rawDescGZIP(), []int{0}
}

func (x *Foo) GetStringField() string {
	if x != nil {
		return x.StringField
	}
	return ""
}

func (x *Foo) GetInt32Field() int32 {
	if x != nil {
		return x.Int32Field
	}
	return 0
}

func (x *Foo) GetInt64Field() int64 {
	if x != nil {
		return x.Int64Field
	}
	return 0
}

func (x *Foo) GetUint32Field() uint32 {
	if x != nil {
		return x.Uint32Field
	}
	return 0
}

func (x *Foo) GetUint64Field() uint64 {
	if x != nil {
		return x.Uint64Field
	}
	return 0
}

func (x *Foo) GetDoubleField() float64 {
	if x != nil {
		return x.DoubleField
	}
	return 0
}

func (x *Foo) GetFloatField() float32 {
	if x != nil {
		return x.FloatField
	}
	return 0
}

func (x *Foo) GetBoolField() bool {
	if x != nil {
		return x.BoolField
	}
	return false
}

func (x *Foo) GetBytesField() []byte {
	if x != nil {
		return x.BytesField
	}
	return nil
}

type Bar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnumField BarEnum_Enum `protobuf:"varint,1,opt,name=enum_field,json=enumField,proto3,enum=proto.BarEnum_Enum" json:"enum_field,omitempty"`
}

func (x *Bar) Reset() {
	*x = Bar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_internal_proto_example_proto_rawDescGZIP(), []int{1}
}

func (x *Bar) GetEnumField() BarEnum_Enum {
	if x != nil {
		return x.EnumField
	}
	return BarEnum_UNKNOWN
}

type BarEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BarEnum) Reset() {
	*x = BarEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_example_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BarEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarEnum) ProtoMessage() {}

func (x *BarEnum) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_example_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarEnum.ProtoReflect.Descriptor instead.
func (*BarEnum) Descriptor() ([]byte, []int) {
	return file_internal_proto_example_proto_rawDescGZIP(), []int{2}
}

type NotGeneratedFoo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NotGeneratedFoo) Reset() {
	*x = NotGeneratedFoo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_example_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotGeneratedFoo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotGeneratedFoo) ProtoMessage() {}

func (x *NotGeneratedFoo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_example_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotGeneratedFoo.ProtoReflect.Descriptor instead.
func (*NotGeneratedFoo) Descriptor() ([]byte, []int) {
	return file_internal_proto_example_proto_rawDescGZIP(), []int{3}
}

func (x *NotGeneratedFoo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NotGeneratedBar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scan string `protobuf:"bytes,1,opt,name=scan,proto3" json:"scan,omitempty"`
}

func (x *NotGeneratedBar) Reset() {
	*x = NotGeneratedBar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_example_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotGeneratedBar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotGeneratedBar) ProtoMessage() {}

func (x *NotGeneratedBar) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_example_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotGeneratedBar.ProtoReflect.Descriptor instead.
func (*NotGeneratedBar) Descriptor() ([]byte, []int) {
	return file_internal_proto_example_proto_rawDescGZIP(), []int{4}
}

func (x *NotGeneratedBar) GetScan() string {
	if x != nil {
		return x.Scan
	}
	return ""
}

var File_internal_proto_example_proto protoreflect.FileDescriptor

var file_internal_proto_example_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x02, 0x0a, 0x03, 0x46, 0x6f, 0x6f, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x75, 0x69, 0x6e,
	0x74, 0x36, 0x34, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b,
	0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x66,
	0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x73, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x39, 0x0a, 0x03,
	0x42, 0x61, 0x72, 0x12, 0x32, 0x0a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x61, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x09, 0x65, 0x6e,
	0x75, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x38, 0x0a, 0x07, 0x42, 0x61, 0x72, 0x45, 0x6e,
	0x75, 0x6d, 0x22, 0x2d, 0x0a, 0x04, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x41, 0x4c, 0x55, 0x45,
	0x5f, 0x31, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x5f, 0x32, 0x10,
	0x02, 0x22, 0x27, 0x0a, 0x0f, 0x4e, 0x6f, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x64, 0x46, 0x6f, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x4e, 0x6f,
	0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x42, 0x61, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x63, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x63, 0x61,
	0x6e, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x79, 0x78, 0x6c, 0x69, 0x6d, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65,
	0x6e, 0x2d, 0x67, 0x6f, 0x2d, 0x73, 0x71, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_example_proto_rawDescOnce sync.Once
	file_internal_proto_example_proto_rawDescData = file_internal_proto_example_proto_rawDesc
)

func file_internal_proto_example_proto_rawDescGZIP() []byte {
	file_internal_proto_example_proto_rawDescOnce.Do(func() {
		file_internal_proto_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_example_proto_rawDescData)
	})
	return file_internal_proto_example_proto_rawDescData
}

var file_internal_proto_example_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_example_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_example_proto_goTypes = []interface{}{
	(BarEnum_Enum)(0),       // 0: proto.BarEnum.Enum
	(*Foo)(nil),             // 1: proto.Foo
	(*Bar)(nil),             // 2: proto.Bar
	(*BarEnum)(nil),         // 3: proto.BarEnum
	(*NotGeneratedFoo)(nil), // 4: proto.NotGeneratedFoo
	(*NotGeneratedBar)(nil), // 5: proto.NotGeneratedBar
}
var file_internal_proto_example_proto_depIdxs = []int32{
	0, // 0: proto.Bar.enum_field:type_name -> proto.BarEnum.Enum
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_example_proto_init() }
func file_internal_proto_example_proto_init() {
	if File_internal_proto_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Foo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_example_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BarEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_example_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotGeneratedFoo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_example_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotGeneratedBar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_example_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_example_proto_goTypes,
		DependencyIndexes: file_internal_proto_example_proto_depIdxs,
		EnumInfos:         file_internal_proto_example_proto_enumTypes,
		MessageInfos:      file_internal_proto_example_proto_msgTypes,
	}.Build()
	File_internal_proto_example_proto = out.File
	file_internal_proto_example_proto_rawDesc = nil
	file_internal_proto_example_proto_goTypes = nil
	file_internal_proto_example_proto_depIdxs = nil
}
